# Generated by Django 4.0.4 on 2022-04-25 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('footbuddyapp', '0003_reply_replier'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='footbuddyapp.room'),
        ),
    ]
