# Generated by Django 4.0.4 on 2022-04-25 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('footbuddyapp', '0004_reply_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='message',
        ),
        migrations.AddField(
            model_name='message',
            name='reply',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='footbuddyapp.reply'),
        ),
    ]
