# Generated by Django 4.0.4 on 2022-04-25 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footbuddyapp', '0006_remove_message_reply_reply_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='replies',
            field=models.TextField(null=True),
        ),
    ]
