# Generated by Django 4.0.4 on 2022-04-25 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footbuddyapp', '0010_alter_message_replies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='replies',
            field=models.TextField(blank=True, default=''),
        ),
    ]
