# Generated by Django 4.0.4 on 2022-04-27 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footbuddyapp', '0012_alter_message_replies'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='topic',
            field=models.TextField(null=True),
        ),
    ]
