# Generated by Django 4.0.4 on 2022-04-27 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footbuddyapp', '0013_message_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='topic',
        ),
        migrations.AddField(
            model_name='room',
            name='topic',
            field=models.TextField(null=True),
        ),
    ]
