# Generated by Django 4.0.4 on 2022-04-27 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('footbuddyapp', '0014_remove_message_topic_room_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='replies',
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
