# Generated by Django 4.0.4 on 2022-04-29 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('footbuddyapp', '0016_remove_room_topic_message_replies_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='replies',
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
